version: "3.8"

services:
  consumer:
    build:
      context: .
      dockerfile: Dockerfile.consumer
    image: kafka-consumer:1.0
    container_name: kafka-consumer
    restart: unless-stopped

    environment:
      - TZ=Asia/Phnom_Penh

    volumes:
      - ./release/config:/app/config:ro
      - /home/kafkaproducer/test_log_file/:/data/logs

